common/models/Area.php
<?php

namespace common\models;

use Yii;
use Zelenin\yii\behaviors\Slug;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "area".
 *
 * @property integer $id
 * @property string $title
 * @property string $slug
 * @property string $image
 * @property string $description
 * @property integer $weight
 * @property integer $created_at
 * @property integer $updated_at
 *
 * @property Event[] $events
 */
class Area extends \yii\db\ActiveRecord
{
    public $uploadImage;
    
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'area';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'image'], 'required'],
            [['description'], 'string'],
            [['weight', 'created_at', 'updated_at'], 'integer'],
            [['title', 'slug', 'image'], 'string', 'max' => 255],
            [['slug'], 'unique'],
            [['uploadImage'], 'safe'],
            [['uploadImage'], 'file', 'extensions'=>'jpg, gif, png'],
        ];
    }
    
    public function behaviors()
    {
        return [
            'slug' => [
                'class' => 'Zelenin\yii\behaviors\Slug',
                'slugAttribute' => 'slug',
                'attribute' => 'title',
                // optional params
                'ensureUnique' => true,
                'replacement' => '-',
                'lowercase' => true,
                'immutable' => false,
                // If intl extension is enabled, see http://userguide.icu-project.org/transforms/general. 
                'transliterateOptions' => 'Russian-Latin/BGN; Any-Latin; Latin-ASCII; NFD; [:Nonspacing Mark:] Remove; NFC;'
            ],
            TimestampBehavior::className(),
            'sortable' => [
                'class' => 'sjaakp\sortable\Sortable',
                'orderAttribute' => 'weight',
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'slug' => 'Slug',
            'image' => 'Image',
            'description' => 'Description',
            'weight' => 'Weight',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEvents()
    {
        return $this->hasMany(Event::className(), ['area_id' => 'id']);
    }

    /**
     * @inheritdoc
     * @return AreaQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new AreaQuery(get_called_class());
    }
}

backend/controllers/AreaController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Area;
use backend\models\AreaSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\UploadedFile;

/**
* AreaController implements the CRUD actions for Area model.
*/
class AreaController extends Controller
{
    /**
    * @inheritdoc
    */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'view', 'create', 'update', 'delete','order'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
    * @inheritdoc
    */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
    * Lists all Area models.
    * @return mixed
    */
    public function actionIndex()
    {
        $searchModel = new AreaSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
    * Displays a single Area model.
    * @param integer $id
    * @return mixed
    */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
    * Creates a new Area model.
    * If creation is successful, the browser will be redirected to the 'view' page.
    * @return mixed
    */
    public function actionCreate()
    {
        $model = new Area();

        if ($model->load(Yii::$app->request->post())) {
            if($image = UploadedFile::getInstance($model, 'uploadImage')){
                $ext = end((explode(".", $image->name)));
                $model->image = Yii::$app->security->generateRandomString().".{$ext}";
                $path = Yii::getAlias('@uploadDir') . DIRECTORY_SEPARATOR . $model->image;
                if(!file_exists(dirname($path)))
                    mkdir(dirname($path), 0777, true); 
            }
            if($model->save()){
                if($image)
                    $image->saveAs($path);
                return $this->redirect(['view', 'id'=>$model->id]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                ]);
            }
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
    * Updates an existing Area model.
    * If update is successful, the browser will be redirected to the 'view' page.
    * @param integer $id
    * @return mixed
    */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            if($image = UploadedFile::getInstance($model, 'uploadImage')){
                $ext = end((explode(".", $image->name)));
                $model->image = Yii::$app->security->generateRandomString().".{$ext}";
                $path = Yii::getAlias('@uploadDir') . DIRECTORY_SEPARATOR . $model->image;
                if(!file_exists(dirname($path)))
                    mkdir(dirname($path), 0777, true);     
            }
            if($model->save()){
                if($image)
                    $image->saveAs($path);
                return $this->redirect(['view', 'id'=>$model->id]);
            } else {
                return $this->render('update', [
                    'model' => $model,
                ]);
            }

            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
    * Deletes an existing Area model.
    * If deletion is successful, the browser will be redirected to the 'index' page.
    * @param integer $id
    * @return mixed
    */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionOrder( )   {
        $post = Yii::$app->request->post( );
        if (isset( $post['key'], $post['pos'] ))   {
            $this->findModel( $post['key'] )->order( $post['pos'] );
        }
    }

    /**
    * Finds the Area model based on its primary key value.
    * If the model is not found, a 404 HTTP exception will be thrown.
    * @param integer $id
    * @return Area the loaded model
    * @throws NotFoundHttpException if the model cannot be found
    */
    protected function findModel($id)
    {
        if (($model = Area::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/controllers/AreaController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\AccessControl;
use common\models\Area;
use frontend\models\AreaSearch;
use frontend\models\EventSearch;
use yii\data\ActiveDataProvider;

/**
* Event controller
*/
class AreaController extends Controller
{
    /**
    * @inheritdoc
    */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index','slug'],
                'rules' => [
                    [
                        'actions' => ['index','slug'],
                        'allow' => true,
                    ],
                ],
            ],
        ];
    }

    /**
    * @inheritdoc
    */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
    * Displays homepage.
    *
    * @return mixed
    */
    public function actionIndex()
    {
        $searchModel = new AreaSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);

    }

    public function actionSlug($slug)
    { 
        $model = Area::find()->where(['slug'=>$slug])->one();
        if (!is_null($model)) {
            $searchModel = new EventSearch();
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams,$model->id);

            return $this->render('view', [
                'model' => $model,
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);      
        } else {
            return $this->redirect('/area/index');
        }
    }
}

frontend/views/area/_post.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\helpers\HtmlPurifier;
use yii\helpers\StringHelper;
use common\components\ImgHelper

?>

<div class="col-md-3 col-sm-6 hero-feature">
    <div class="thumbnail">
        <?php if($model->image && ImgHelper::exist($model->image)): ?>
            <?=Html::img(Yii::$app->urlManager->baseUrl . '/image/'.$model->image, ['alt'=>$model->image, 'class'=>'img-responsive'])?>
            <?php else : ?>
            <img class="img-responsive" src="http://placehold.it/800x500" alt="">
        <?php endif;?>
        <div class="caption">
            <h3><?=$model->title;?></h3>
            <p class=""><?= HtmlPurifier::process(StringHelper::truncateWords($model->description,20)) ?></p>
            <p>
                <?=Html::a(Html::encode('Show Events'), Url::to(['area/slug', 'slug' => $model->slug]),['class'=>'btn btn-default'])?>
            </p>
        </div>
    </div>
</div>

frontend/views/area/index.php
<?php
use yii\widgets\ListView;

/* @var $this yii\web\View */

$this->title = 'Areas';
$this->params['breadcrumbs'][] = $this->title;
?>

<!-- Page Header -->
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Areas
            <small>List</small>
        </h1>
    </div>
</div>
<!-- /.row -->

    <?php
    echo ListView::widget([
        'dataProvider' => $dataProvider,
        'itemView' => function ($model, $key, $index, $widget) use($dataProvider){
            if($index == 0){
                echo '<!-- Areas Row -->';
                echo '<div class="row text-center">';
            }    
            if($index != 0 && $index % 4 == 0  && ($index) != $dataProvider->count){   
                echo '</div>';
                echo '<!-- /.row -->';
                echo '<!-- Areas Row -->';
                echo '<div class="row  text-center">';
            }
            echo Yii::$app->controller->renderPartial('_post',['model'=>$model]);
            if(($index+1) == $dataProvider->count){
                echo '</div>';
                echo '<!-- /.row -->';
            }       
        },
    ]);
    ?>

frontend/views/area/view.php
<?php
use yii\widgets\ListView;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\helpers\HtmlPurifier;
use yii\helpers\StringHelper;
use common\components\ImgHelper;

/* @var $this yii\web\View */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Areas', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<!-- Jumbotron Header -->
<header class="jumbotron hero-spacer">
    <div class="image pull-left" style="width:65%">
    <?php if($model->image && ImgHelper::exist($model->image)): ?>
        <?=Html::img(Yii::$app->urlManager->baseUrl . '/image/'.$model->image, ['alt'=>$model->image, 'class'=>'img-responsive','data-scale'=>'0.38'])?>
        <?php else : ?>
        <img class="img-responsive"  src="http://placehold.it/900x350" alt="" >
    <?php endif;?>
    </div>
    <h2><?=$model->title;?></h2>
    <p><?= HtmlPurifier::process(StringHelper::truncateWords($model->description,20)) ?></p>
    </p>
</header>

<hr>

<!-- Title -->
<div class="row">
    <div class="col-lg-12">
        <h3>Events</h3>
    </div>
</div>
<!-- /.row -->

<?php
echo ListView::widget([
    'dataProvider' => $dataProvider,
    'itemView' => function ($model, $key, $index, $widget) use($dataProvider){
        if($index == 0){
            echo '<!-- Areas Row -->';
            echo '<div class="row text-center">';
        }    
        if($index != 0 && $index % 3 == 0  && ($index) != $dataProvider->count){   
            echo '</div>';
            echo '<!-- /.row -->';
            echo '<!-- Areas Row -->';
            echo '<div class="row  text-center">';
        }
        echo Yii::$app->controller->renderPartial('/event/_post',['model'=>$model]);
        if(($index+1) == $dataProvider->count){
            echo '</div>';
            echo '<!-- /.row -->';
        }       
    },
]);
?>